### PR TITLE
Only show output for the file being edited, add error limit option

### PR DESCRIPTION
**Pull request by m-bra**
-> Issue: Warnings from other files #13 
Add an error limit option, defaults to NO LIMIT -> all errors shown.
Also fix for PR: Project specific include paths #11

### CODE REVIEW

**Comment by hd-deman** [comment]
@Snake231088 can you review this?

**Comment by Snake231088** [comment]
I tried but not work

**Comment by m-bra** [comment]
Made a commit

**Comment by Snake231088** [comment]
i close because i merged the commit manually and i updated linter-clang and now only issue for current file are show.
The only problem now is that the include path contains blank space the command not work. I tried with " " and \  but not work.

**Comment by m-bra** [comment]
Can you give the output of the clang module? (console output in dev mode)

**Pull request closed without merging**
