### PR TITLE
Fix for PR #21 with filenames with blank spaces

### PR DESCRIPTION
**Pull request by m-bra**
@Snake231088 this should fix your problem. (Commit e708fdd)

### CODE REVIEW

**Comment by Snake231088** [comment]
Also with quote not work.
I'm trying in this moment but also with \" not work. For example the output is:
activate linter-clang
index.js:64 Window load time: 1558ms
linter-clang.coffee:36 clang-command: clang
linter-clang.coffee:80 is node executable: false
linter-clang.coffee:104 command = clang, args = -fsyntax-only,-fno-caret-diagnostics,-fexceptions,-x,c++,-std=c++11,-Wall,-ferror-limit=0,-I,.,-I,"/Users/snake/Google,Drive/Progetti/C++/Programmazione,Di,Sistema/Lab,4",/var/folders/q6/chyv15m12_bclp_wmk_n2thh0000gn/T/AtomLinter115020-2293-1o980ersource.cpp/example.cpp, options = [object Object]
linter-clang.coffee:99 stderr clang: error: no such file or directory: 'Drive/Progetti/C++/Programmazione'
clang: error: no such file or directory: 'Di'
clang: error: no such file or directory: 'Sistema/Lab'
clang: error: no such file or directory: '4"'

linter-clang.coffee:36 clang-command: clang
linter-clang.coffee:80 is node executable: false
linter-clang.coffee:104 command = clang, args = -fsyntax-only,-fno-caret-diagnostics,-fexceptions,-x,c++,-std=c++11,-Wall,-ferror-limit=0,-I,.,-I,"/Users/snake/Google,Drive/Progetti/C++/Programmazione,Di,Sistema/Lab,4",/var/folders/q6/chyv15m12_bclp_wmk_n2thh0000gn/T/AtomLinter115020-2293-23k03esource.cpp/example.cpp, options = [object Object]
linter-clang.coffee:99 stderr clang: error: no such file or directory: 'Drive/Progetti/C++/Programmazione'
clang: error: no such file or directory: 'Di'
clang: error: no such file or directory: 'Sistema/Lab'
clang: error: no such file or directory: '4"'

**Comment by m-bra** [comment]
@Snake231088 Made new commit. The problem was that filenames with spaces were treated as multiple arguments, not by clang but by getCmdAndArgs(). Fixed that, tried path with spaces, worked.

**Comment by Snake231088** [comment]
Thanks!!!It workS!!!

**Comment by m-bra** [comment]
Finally!

**Pull request closed without merging**
