### PR TITLE
[WIP] Set working directory.

### LINKED ISSUE #102: Doesn't run clang from CWD!
Hi,

Suppose we have project a directory/file hierarchy as following
project
- test.cpp
- include/
  - test.hpp

test.cpp includes test.hpp

Start atom from the 'project' directory.
If in the linter-clang include path option we give "include" (without quotes), the linter complains that it can not find the test.hpp.
However, if you run manually whatever the linter-clang runs it's fine no errors.
I've found after some digging that the cwd for the clang command from the clang-linter is the root (/) directory instead of the project directory. So if you give the absolute path of the include directory is fine. But this is wrong IMHO, the include paths given to the linter-clang settings must be relative to the cwd.

### PR DESCRIPTION
**Pull request by keplersj**
Fixes #102.

### CODE REVIEW

**Comment by kepler0** [comment]
@FirstTimeInForever, @jgiokas, could you test this for me and tell me if it fixes your problem?

**Comment by smlewis** [comment]
Was there any action here?  I think this is the problem I'm having too.

**Comment by keplersj** [comment]
@smlewis Because I could never reproduce the issue I was waiting for verification that this patch fixes it. If you could test this patch and verify it fixes your issue, I'll merge and publish it.

**Comment by smlewis** [comment]
I'm willing to give it a try, but there's a pair of pretty big caveats: I only started using Atom last week and I only started playing around with linter today.  It's entirely possible I'm suffering from PEBKAC with the linter-clang issue I see and it's certainly true that I don't know where to start with building/using a dev version of a plugin.  I assume there's good generic documentation for plugin developers somewhere?

**Comment by smlewis** [comment]
I can confirm that this development branch fixes the issue within a toy project similar to the one described in issue #102.  It doesn't seem to fix my actual problem, but it does show improved behavior for the narrower problem the issue describes.

**Comment by Arcanemagus** [comment]
Handled in #191.

**Pull request closed without merging**
